

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function TermsPage() {
  return (
    <div className="container mx-auto max-w-4xl py-12 md:py-20">
      <Card>
        <CardHeader className="text-center">
          <CardTitle className="text-3xl font-bold tracking-tight text-primary sm:text-4xl">Terms of Service</CardTitle>
          <p className="pt-2 text-sm text-muted-foreground">Last updated: May 21, 2024</p>
        </CardHeader>
        <CardContent className="prose prose-lg dark:prose-invert mx-auto max-w-none">
          <p>
            Please read these terms of service ("Terms", "Terms of Service") carefully before using the RealPrompt website (the "Service") operated by Us.
          </p>

          <h2>1. Use of Service</h2>
          <p>
            The Service and its original content, features, and functionality are and will remain the exclusive property of RealPrompt and its licensors. The prompts provided are for personal and commercial use.
          </p>

          <h2>2. Content</h2>
          <p>
            Our Service allows you to access and use prompts ("Content"). We are not responsible for the output generated by AI models based on this Content. You are responsible for ensuring that your use of the generated output complies with all applicable laws and does not infringe on the rights of third parties.
          </p>

          <h2>3. Disclaimer</h2>
          <p>
            The Service is provided on an "AS IS" and "AS AVAILABLE" basis. We make no warranties, express or implied, regarding the accuracy, reliability, or availability of the Service or its Content.
          </p>

          <h2>4. Termination</h2>
          <p>
            We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
          </p>

          <h2>5. Changes to Service</h2>
          <p>
            We reserve the right to withdraw or amend our Service, and any service or material we provide via the Service, in our sole discretion without notice.
          </p>

          <h2>Contact Us</h2>
          <p>
            If you have any questions about these Terms, please contact us.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
